version: "3.8"

services:
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"  # HTTP Proxy
      - "8443:8443"  # HTTPS Proxy
      - "8001:8001"  # Admin API
      - "8444:8444"  # Admin API HTTPS
      - "8002:8002"  # Kong Manager (Admin UI)
    command: [ "kong", "docker-start" ]
